### ISSUE TITLE
servo only works between 0 and 90 degrees

### ISSUE THREAD

**Issue by zarmath** [DFRobot/pxt-motor#3]
servo only works between 0 and 90 degrees, If I set a value higher than 90 degrees the servo does not act.

**Comment by tsobika** [comment]
Even here wondering have the same problem. Using the servo the tower pro mg996r, and same micro servo 9g is. The negative I think so you can not correspond to the angle specified.

**Comment by tsobika** [comment]
DFRobot pxt-motor expansion block used somehow. Angle designation We accepted that it operates roughly 180 degrees in the range of about 30 to 70 and converted it from 0 to 180 degrees. Because it seems different for each servo, I thought there might be settings.
